/**
 * Service for loading ayah-level and word-level timing data.
 *
 * Lazy-loads timing JSON from /data/timings/{surahNumber}.json (ayah-level)
 * and /data/timings-words/{surahNumber}.json (word-level).
 * Generated by scripts/build-timings.ts from aligner output.
 */

import type { WordTiming } from '@/types/recitation';

interface AyahTiming {
  ayah: number;
  start: number;
  end: number;
}

interface SurahTimings {
  surah: number;
  ayahs: AyahTiming[];
}

interface WordTimingEntry {
  word: string;
  ref: string;
  start: number;
  end: number;
}

interface AyahWordTimings {
  ayah: number;
  words: WordTimingEntry[];
}

interface SurahWordTimings {
  surah: number;
  ayahs: AyahWordTimings[];
}

class AyahTimingService {
  private cache: Map<number, SurahTimings> = new Map();
  private wordCache: Map<number, SurahWordTimings> = new Map();

  async loadSurahTimings(surah: number): Promise<SurahTimings | null> {
    if (this.cache.has(surah)) {
      return this.cache.get(surah)!;
    }

    try {
      const res = await fetch(`/data/timings/${surah}.json`);
      if (!res.ok) return null;

      const data: SurahTimings = await res.json();
      this.cache.set(surah, data);
      return data;
    } catch {
      return null;
    }
  }

  async getAyahRange(
    surah: number,
    startAyah: number,
    endAyah: number
  ): Promise<{ startTime: number; endTime: number } | null> {
    const timings = await this.loadSurahTimings(surah);
    if (!timings) return null;

    const startTiming = timings.ayahs.find(a => a.ayah === startAyah);
    const endTiming = timings.ayahs.find(a => a.ayah === endAyah);

    if (!startTiming || !endTiming) return null;

    return {
      startTime: startTiming.start,
      endTime: endTiming.end,
    };
  }

  /**
   * Load word-level timing data for a surah.
   */
  async loadSurahWordTimings(surah: number): Promise<SurahWordTimings | null> {
    if (this.wordCache.has(surah)) {
      return this.wordCache.get(surah)!;
    }

    try {
      const res = await fetch(`/data/timings-words/${surah}.json`);
      if (!res.ok) return null;

      const data: SurahWordTimings = await res.json();
      this.wordCache.set(surah, data);
      return data;
    } catch {
      return null;
    }
  }

  /**
   * Get word-level timings for a specific ayah.
   */
  async getWordTimings(surah: number, ayah: number): Promise<WordTiming[] | null> {
    const data = await this.loadSurahWordTimings(surah);
    if (!data) return null;

    const ayahData = data.ayahs.find(a => a.ayah === ayah);
    if (!ayahData) return null;

    return ayahData.words.map(w => ({
      word: w.word,
      wordRef: w.ref,
      start: w.start,
      end: w.end,
    }));
  }

  /**
   * Get timing for a specific word by its word reference.
   * wordRef format: "surah:ayah:wordIndex"
   */
  async getWordTiming(wordRef: string): Promise<WordTiming | null> {
    const parts = wordRef.split(':');
    if (parts.length !== 3) return null;

    const surah = parseInt(parts[0]);
    const ayah = parseInt(parts[1]);
    const wordTimings = await this.getWordTimings(surah, ayah);
    if (!wordTimings) return null;

    return wordTimings.find(w => w.wordRef === wordRef) || null;
  }
}

export const ayahTimingService = new AyahTimingService();
