/**
 * Service for loading ayah-level timing data.
 *
 * Lazy-loads timing JSON from /data/timings/{surahNumber}.json,
 * which is generated by scripts/build-timings.ts from aligner output.
 */

interface AyahTiming {
  ayah: number;
  start: number;
  end: number;
}

interface SurahTimings {
  surah: number;
  ayahs: AyahTiming[];
}

class AyahTimingService {
  private cache: Map<number, SurahTimings> = new Map();

  async loadSurahTimings(surah: number): Promise<SurahTimings | null> {
    if (this.cache.has(surah)) {
      return this.cache.get(surah)!;
    }

    try {
      const res = await fetch(`/data/timings/${surah}.json`);
      if (!res.ok) return null;

      const data: SurahTimings = await res.json();
      this.cache.set(surah, data);
      return data;
    } catch {
      return null;
    }
  }

  async getAyahRange(
    surah: number,
    startAyah: number,
    endAyah: number
  ): Promise<{ startTime: number; endTime: number } | null> {
    const timings = await this.loadSurahTimings(surah);
    if (!timings) return null;

    const startTiming = timings.ayahs.find(a => a.ayah === startAyah);
    const endTiming = timings.ayahs.find(a => a.ayah === endAyah);

    if (!startTiming || !endTiming) return null;

    return {
      startTime: startTiming.start,
      endTime: endTiming.end,
    };
  }
}

export const ayahTimingService = new AyahTimingService();
